services:
  teamfinder.api:
    image: teamfinder.api
    build:
      context: .
      dockerfile: TeamFinder.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DP_KEYS_FOLDER: "/keys"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      JWT_KEY: "${JWT_KEY}"
      JWT_ISSUER: "MiniApp"
      JWT_AUDIENCE: "MiniApp"
      ENABLE_DEV_AUTH: "${ENABLE_DEV_AUTH}"
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=teamfinderdb;Username=postgres;Password=postgres"
      RUN_MIGRATIONS: "true"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
    volumes:
      - teamfinder-keys:/keys
  client:
    build:
      context: ../miniapp
      dockerfile: Dockerfile
    depends_on:
      - teamfinder.api
    ports:
      - "5173:80"
  
  postgres:
    image: postgres:18.3
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "teamfinderdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  teamfinder-keys:
  postgres_data: