// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamFinder.Postgresql;

#nullable disable

namespace TeamFinder.Postgresql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427192707_makeInactiveTeam")]
    partial class makeInactiveTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamFinder.Postgresql.Model.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.JoinRequestEntity", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "ProfileId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("TgId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.ProfileSkillEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("ProfileId", "SkillId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.SkillClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("AncestorId");

                    b.HasIndex("DescendantId");

                    b.ToTable("skill_closure", (string)null);
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.SkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EventEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EventStart")
                        .HasColumnType("date");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.TeamMemberEntity", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "ProfileId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.WantedProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("WantedProfiles");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.WantedProfileSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WantedProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WantedProfileId");

                    b.ToTable("WantedProfileSkills");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.InvitationEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.TeamEntity", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.JoinRequestEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.TeamEntity", null)
                        .WithMany("JoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.ProfileEntity", b =>
                {
                    b.OwnsOne("TeamFinder.Postgresql.Model.GithubEntity", "GithubInfo", b1 =>
                        {
                            b1.Property<Guid>("ProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GithubId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProfileUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RepositoriesCount")
                                .HasColumnType("integer");

                            b1.Property<string>("TopLanguage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("TotalStars")
                                .HasColumnType("integer");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileEntityId");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileEntityId");
                        });

                    b.Navigation("GithubInfo");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.ProfileSkillEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.ProfileEntity", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFinder.Postgresql.Model.SkillEntity", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.SkillClosure", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.SkillEntity", "Ancestor")
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamFinder.Postgresql.Model.SkillEntity", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.TeamMemberEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.WantedProfileEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.TeamEntity", "Team")
                        .WithMany("WantedProfiles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.WantedProfileSkillEntity", b =>
                {
                    b.HasOne("TeamFinder.Postgresql.Model.WantedProfileEntity", "WantedProfile")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("WantedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedProfile");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.ProfileEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.TeamEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("WantedProfiles");
                });

            modelBuilder.Entity("TeamFinder.Postgresql.Model.WantedProfileEntity", b =>
                {
                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
